name: C Build and Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GCC
        run: sudo apt update && sudo apt install -y build-essential

      - name: Compile C Program
        run: gcc main.c -o main

      - name: Run Program
        run: ./main
